"""
Server-side résumé PDF generation (fpdf2 — pure Python, no system deps).

Produces a clean one-page résumé from a worker's structured profile + credentials
+ AI summary. Verified credentials are marked with their tier so the document
itself carries the SKILLED trust signal. Pure: returns bytes, no I/O — unit-tested.
"""
from __future__ import annotations

from typing import Any

from fpdf import FPDF

# Brand palette (Cohere editorial).
_GREEN = (0, 60, 51)
_INK = (33, 33, 33)
_SLATE = (82, 82, 91)
_HAIR = (217, 217, 221)


def _txt(s: Any) -> str:
    # fpdf2 core fonts are latin-1; strip anything that can't encode.
    return str(s or "").encode("latin-1", "replace").decode("latin-1")


def build_resume_pdf(profile: dict[str, Any], summary: str | None = None) -> bytes:
    pdf = FPDF(format="Letter", unit="pt")
    pdf.set_auto_page_break(auto=True, margin=48)
    pdf.add_page()
    pdf.set_margins(48, 44, 48)
    width = pdf.w - 96

    # Header — name + trade
    pdf.set_text_color(*_INK)
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 28, _txt(profile.get("name") or "SKILLED Worker"), ln=1)

    sub = " · ".join(
        p for p in [
            profile.get("trade") or profile.get("program"),
            ", ".join(q for q in [profile.get("city"), profile.get("state")] if q),
        ] if p
    )
    if sub:
        pdf.set_text_color(*_SLATE)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 16, _txt(sub), ln=1)

    contact_bits = []
    if profile.get("email"):
        contact_bits.append(profile["email"])
    if profile.get("available_from"):
        contact_bits.append(f"Available {profile['available_from']}")
    if profile.get("willing_to_relocate"):
        contact_bits.append("Open to relocation")
    if contact_bits:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_SLATE)
        pdf.cell(0, 14, _txt(" · ".join(contact_bits)), ln=1)

    pdf.ln(6)
    _rule(pdf, width)

    # Summary
    if summary:
        _section(pdf, "Summary")
        pdf.set_font("Helvetica", "", 10.5)
        pdf.set_text_color(*_INK)
        pdf.multi_cell(width, 15, _txt(summary))
        pdf.ln(8)

    # Credentials
    creds = profile.get("credentials") or []
    if creds:
        _section(pdf, "Credentials & Licenses")
        for c in creds:
            badge = c.get("badge") or "Self-Reported"
            pdf.set_font("Helvetica", "B", 10.5)
            pdf.set_text_color(*_INK)
            name = c.get("name") or c.get("raw_name") or "Credential"
            # Name (left) + badge (right)
            pdf.cell(width * 0.7, 15, _txt(name))
            pdf.set_font("Helvetica", "", 8.5)
            is_verified = badge != "Self-Reported"
            pdf.set_text_color(*(_GREEN if is_verified else _SLATE))
            pdf.cell(width * 0.3, 15, _txt(badge), align="R", ln=1)
            meta = " · ".join(
                p for p in [c.get("credential_type"), c.get("issuer")] if p
            )
            if meta:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*_SLATE)
                pdf.cell(0, 13, _txt(meta), ln=1)
            pdf.ln(3)

    # Footer trust line
    pdf.set_y(-46)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*_SLATE)
    vcount = sum(1 for c in creds if (c.get("badge") and c["badge"] != "Self-Reported"))
    pdf.cell(
        0, 12,
        _txt(f"Generated by SKILLED Pro · {vcount} SKILLED-verified credential(s) on file."),
        align="C",
    )

    out = pdf.output()
    return bytes(out)


def _section(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(*_GREEN)
    pdf.cell(0, 14, _txt(title.upper()), ln=1)


def _rule(pdf: FPDF, width: float) -> None:
    pdf.set_draw_color(*_HAIR)
    y = pdf.get_y()
    pdf.line(48, y, 48 + width, y)
    pdf.ln(8)
