-- GENERATED by scripts/gen_taxonomy.py from 'Industry & Career List Revisions v2'.
-- SKILLED Nation two-level taxonomy: sectors + career fields.

CREATE TABLE IF NOT EXISTS public.sectors (
  code          TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  full_name     TEXT NOT NULL,
  description   TEXT NOT NULL DEFAULT '',
  examples      TEXT NOT NULL DEFAULT '',
  display_order INT  NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.sectors (code, name, full_name, description, examples, display_order)
VALUES ('construction', 'Construction & Building Trades', 'Construction & Building Trades', 'Building, renovating, and repairing homes, commercial buildings, roads, bridges, and other structures.', 'Carpenter, electrician, plumber, HVAC technician, mason, roofer, welder, heavy equipment operator', 0)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, full_name = EXCLUDED.full_name,
  description = EXCLUDED.description, examples = EXCLUDED.examples,
  display_order = EXCLUDED.display_order;
INSERT INTO public.sectors (code, name, full_name, description, examples, display_order)
VALUES ('manufacturing', 'Manufacturing', 'Manufacturing', 'Making physical products using machinery, tools, robotics, automation, machining, and quality-control systems. Includes traditional factory work as well as high-tech production.', 'CNC machinist, industrial maintenance technician, welder/fabricator, tool-and-die maker, mechatronics technician, robotics technician', 1)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, full_name = EXCLUDED.full_name,
  description = EXCLUDED.description, examples = EXCLUDED.examples,
  display_order = EXCLUDED.display_order;
INSERT INTO public.sectors (code, name, full_name, description, examples, display_order)
VALUES ('energy', 'Energy & Utilities', 'Energy & Utilities', 'Producing, transmitting, distributing, and maintaining energy, water, gas, and related utility systems. This includes both traditional utilities and clean-energy pathways.', 'Lineworker, power plant operator, solar PV installer, wind turbine technician, substation technician, natural gas technician', 2)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, full_name = EXCLUDED.full_name,
  description = EXCLUDED.description, examples = EXCLUDED.examples,
  display_order = EXCLUDED.display_order;
INSERT INTO public.sectors (code, name, full_name, description, examples, display_order)
VALUES ('transportation', 'Transportation', 'Transportation (Automotive, Diesel, Aviation, Marine, Rail, and Related Logistics)', 'Maintaining and repairing cars, trucks, buses, construction equipment, farm equipment, aircraft, rail and railcars, boats and marine craft, and other motorized systems.', 'Auto technician, diesel mechanic, collision repair technician, small engine mechanic, heavy equipment mechanic, aircraft mechanic, avionics technician, marine technician, shipfitter, rail signal maintainer, locomotive technician', 3)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, full_name = EXCLUDED.full_name,
  description = EXCLUDED.description, examples = EXCLUDED.examples,
  display_order = EXCLUDED.display_order;
INSERT INTO public.sectors (code, name, full_name, description, examples, display_order)
VALUES ('healthcare', 'Healthcare', 'Healthcare', 'Hands-on clinical, technical, and patient-support roles that typically require certificates, licenses, or associate-level training rather than a four-year degree', 'Medical assistant, nurse, surgical technologist, dental assistant, pharmacy technician, phlebotomist, radiologic technologist, sterile processing technician; cosmetology', 4)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, full_name = EXCLUDED.full_name,
  description = EXCLUDED.description, examples = EXCLUDED.examples,
  display_order = EXCLUDED.display_order;
INSERT INTO public.sectors (code, name, full_name, description, examples, display_order)
VALUES ('data_it', 'Data & Information Technology', 'Data & Information Technology', 'Building, maintaining, and repairing infrastructure, hardware, and software related to information technology and data storage. Primarily focused on non-4 year and advanced degrees.', 'Database administrators, network and IT support specialist, network and computer systems administrator,', 5)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, full_name = EXCLUDED.full_name,
  description = EXCLUDED.description, examples = EXCLUDED.examples,
  display_order = EXCLUDED.display_order;
INSERT INTO public.sectors (code, name, full_name, description, examples, display_order)
VALUES ('telecom', 'Telecommunications', 'Telecommunications', 'Installing, maintaining, and troubleshooting the physical systems that support internet, phone, security, data, and connected-building technologies. This overlaps with construction, utilities, and IT.', 'Fiber optic technician, cable installer, low-voltage electrical technician, security systems installer, network cabling technician', 6)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, full_name = EXCLUDED.full_name,
  description = EXCLUDED.description, examples = EXCLUDED.examples,
  display_order = EXCLUDED.display_order;
INSERT INTO public.sectors (code, name, full_name, description, examples, display_order)
VALUES ('public_safety', 'Public & Emergency Service', 'Public & Emergency Service', 'Careers focused on protecting people, property, and communities. Not all public safety jobs are “trades” in the traditional sense, but many are hands-on, skill-based, credentialed career paths.', 'Firefighter, EMT/paramedic, fire alarm technician, emergency vehicle technician, public safety communications technician, various municipal and civil service positions', 7)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, full_name = EXCLUDED.full_name,
  description = EXCLUDED.description, examples = EXCLUDED.examples,
  display_order = EXCLUDED.display_order;

ALTER TABLE public.canonical_job_families ADD COLUMN IF NOT EXISTS is_other BOOLEAN NOT NULL DEFAULT FALSE;

-- Career fields land in canonical_job_families (code = field code,
-- industries[] = sector codes) so every existing FK keeps working.
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('ai_and_machine_learning', 'AI and Machine Learning', ARRAY['AI and Machine Learning']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('additive_manufacturing', 'Additive Manufacturing & 3D Printing', ARRAY['Additive Manufacturing & 3D Printing']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('aviation_maintenance', 'Aircraft/Aviation Maintenance (including A&P Mechanic)', ARRAY['Aircraft/Aviation Maintenance (including A&P Mechanic)']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('architectural_drafting_cad', 'Architectural Drafting/CAD', ARRAY['Architectural Drafting/CAD']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('auto_body_collision', 'Auto Body / Collision Repair', ARRAY['Auto Body / Collision Repair']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('automotive_ev_service', 'Automotive and EV Service & Technology', ARRAY['Automotive and EV Service & Technology']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('biomedical_equipment_technology', 'Biomedical Equipment Technology', ARRAY['Biomedical Equipment Technology']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('building_and_facilities_maintenance', 'Building & Facilities Maintenance', ARRAY['Building & Facilities Maintenance']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('building_automation_controls', 'Building Automation & Controls', ARRAY['Building Automation & Controls']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('building_construction_technology', 'Building Construction Technology', ARRAY['Building Construction Technology']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('building_energy_management', 'Building Energy Management', ARRAY['Building Energy Management']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('cnc_machining', 'CNC Machining & Precision Machining', ARRAY['CNC Machining & Precision Machining']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('fiber_optics_technician', 'Cable/Fiber Optics Technician', ARRAY['Cable/Fiber Optics Technician']::text[], '{telecom}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('cardiovascular_sonography', 'Cardiovascular Sonography', ARRAY['Cardiovascular Sonography','Cardovascular Sonography']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('cardiovascular_technician', 'Cardiovascular Technician', ARRAY['Cardiovascular Technician']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('carpentry_and_woodworking', 'Carpentry & Woodworking', ARRAY['Carpentry & Woodworking']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('cloud_computing_and_infrastructure', 'Cloud Computing & Infrastructure', ARRAY['Cloud Computing & Infrastructure']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('commercial_driving_cdl', 'Commercial Driving (CDL)', ARRAY['Commercial Driving (CDL)']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('computer_engineering', 'Computer Engineering', ARRAY['Computer Engineering']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('computer_systems_administration', 'Computer Systems Administration', ARRAY['Computer Systems Administration']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('construction_management', 'Construction Management', ARRAY['Construction Management']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('cosmetology_esthetician', 'Cosmetology / Esthetician', ARRAY['Cosmetology / Esthetician']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('cybersecurity', 'Cybersecurity', ARRAY['Cybersecurity']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('data_center_operations', 'Data Center Operations', ARRAY['Data Center Operations']::text[], '{data_it,telecom}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('data_science_and_analytics', 'Data Science & Analytics', ARRAY['Data Science & Analytics']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('database_administration', 'Database Administration', ARRAY['Database Administration']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('dental_assistant', 'Dental Assistant', ARRAY['Dental Assistant']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('dental_hygienist', 'Dental Hygienist', ARRAY['Dental Hygienist']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('diagnostic_medical_sonography', 'Diagnostic Medical Sonography', ARRAY['Diagnostic Medical Sonography']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('diesel_service_and_technology', 'Diesel Service & Technology', ARRAY['Diesel Service & Technology']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('diet_nutrition', 'Diet & Nutrition', ARRAY['Diet & Nutrition']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('emt_paramedic', 'EMT / Paramedic', ARRAY['EMT / Paramedic']::text[], '{healthcare,public_safety}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('electrical', 'Electrical (Residential or Commercial)', ARRAY['Electrical (Residential or Commercial)']::text[], '{construction,energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('electrical_engineering', 'Electrical Engineering', ARRAY['Electrical Engineering']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('transmission_linework', 'Electrical/Transmission Linework', ARRAY['Electrical/Transmission Linework']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('energy_storage', 'Energy Storage', ARRAY['Energy Storage']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('exercise_science_and_sports_medicine', 'Exercise Science & Sports Medicine', ARRAY['Exercise Science & Sports Medicine']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('fire_science', 'Fire Science', ARRAY['Fire Science']::text[], '{public_safety}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('gis', 'Geographic Information Systems (GIS)', ARRAY['Geographic Information Systems (GIS)']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('hvac_r', 'HVAC/R', ARRAY['HVAC/R']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('healthcare_system_administration', 'Healthcare System Administration', ARRAY['Healthcare System Administration']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('heavy_equipment_operation', 'Heavy Equipment Operation', ARRAY['Heavy Equipment Operation']::text[], '{construction,energy,transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('heavy_equipment_service_and_technology', 'Heavy Equipment Service & Technology', ARRAY['Heavy Equipment Service & Technology']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('home_and_building_inspection', 'Home & Building Inspection', ARRAY['Home & Building Inspection']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('it_network_support', 'IT & Network Support', ARRAY['IT & Network Support']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('industrial_electrical_technology', 'Industrial Electrical Technology', ARRAY['Industrial Electrical Technology']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('industrial_maintenance', 'Industrial Maintenance, Millwright & Mechanical Systems', ARRAY['Industrial Maintenance, Millwright & Mechanical Systems']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('metrology_cmm', 'Inspection, Metrology & CMM Operation', ARRAY['Inspection, Metrology & CMM Operation']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('instrumentation_controls', 'Instrumentation and Controls', ARRAY['Instrumentation and Controls']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('instrumentation_automation_controls', 'Instrumentation, Automation, & Controls', ARRAY['Instrumentation, Automation, & Controls']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('interior_finishing', 'Interior Finishing (e.g., Flooring, Drywall, Insulation, Painting, Interior Design)', ARRAY['Interior Finishing (e.g., Flooring, Drywall, Insulation, Painting, Interior Design)']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('laboratory_technician', 'Laboratory Technician', ARRAY['Laboratory Technician']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('law_enforcement', 'Law Enforcement / Criminology', ARRAY['Law Enforcement / Criminology']::text[], '{public_safety}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('lowvoltage_electrical_technology', 'Low-Voltage Electrical Technology', ARRAY['Low-Voltage Electrical Technology']::text[], '{construction,energy,telecom}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('mri_technician', 'MRI Technician', ARRAY['MRI Technician']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('manufacturing_engineering_tech', 'Manufacturing Engineering Technology & Industrial Technology', ARRAY['Manufacturing Engineering Technology & Industrial Technology']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('manufacturing_production', 'Manufacturing Production & Machine Operation', ARRAY['Manufacturing Production & Machine Operation']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('marine_systems_service', 'Marine Systems Service & Technology', ARRAY['Marine Systems Service & Technology']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('marine_welding', 'Marine Welding', ARRAY['Marine Welding']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('masonry_and_concrete', 'Masonry and Concrete', ARRAY['Masonry and Concrete']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('massage_therapy', 'Massage Therapy', ARRAY['Massage Therapy']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('materials_ndt', 'Materials Testing & Nondestructive Testing', ARRAY['Materials Testing & Nondestructive Testing']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('mechanical_design_cad_cam', 'Mechanical Design, CAD/CAM & Drafting', ARRAY['Mechanical Design, CAD/CAM & Drafting','Mechancial Design, CAD/CAM & Drafting']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('medical_assistant', 'Medical Assistant', ARRAY['Medical Assistant']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('medical_billing_and_coding', 'Medical Billing and Coding', ARRAY['Medical Billing and Coding']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('health_information', 'Medical Records and Health Information', ARRAY['Medical Records and Health Information']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('powersports_service', 'Motorcycle / Powersports Service & Technology', ARRAY['Motorcycle / Powersports Service & Technology']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('network_cabling_technician', 'Network Cabling Technician', ARRAY['Network Cabling Technician']::text[], '{telecom}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('network_operations', 'Network Operations', ARRAY['Network Operations']::text[], '{telecom}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('nursing', 'Nursing (LPN/LVN, ADN, RN)', ARRAY['Nursing (LPN/LVN, ADN, RN)']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('nursing_assistant', 'Nursing Assistant (CNA)', ARRAY['Nursing Assistant (CNA)']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('occupational_therapy_assistant', 'Occupational Therapy Assistant', ARRAY['Occupational Therapy Assistant']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('oil_gas_production', 'Oil / Natural Gas Production Technology', ARRAY['Oil / Natural Gas Production Technology']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('patient_care', 'Patient Care', ARRAY['Patient Care']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('pharmacy_technician', 'Pharmacy Technician', ARRAY['Pharmacy Technician']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('phlebotomist', 'Phlebotomist', ARRAY['Phlebotomist']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('physical_therapy_assistant', 'Physical Therapy Assistant', ARRAY['Physical Therapy Assistant']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('pipefitting_steamfitting', 'Pipefitting / Steamfitting', ARRAY['Pipefitting / Steamfitting']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('pipeline_construction', 'Pipeline Construction and Operation', ARRAY['Pipeline Construction and Operation']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('pipeline_welding', 'Pipeline Welding', ARRAY['Pipeline Welding']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('plastics_composites', 'Plastics, Polymers & Composites Manufacturing', ARRAY['Plastics, Polymers & Composites Manufacturing']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('plumbing', 'Plumbing', ARRAY['Plumbing']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('power_plant_operation', 'Power Plant Technology/Operation', ARRAY['Power Plant Technology/Operation']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('process_technology_and_plant_operations', 'Process Technology & Plant Operations', ARRAY['Process Technology & Plant Operations']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('qa_testing_and_automation', 'QA Testing and Automation', ARRAY['QA Testing and Automation']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('quality_control_and_quality_assurance', 'Quality Control & Quality Assurance', ARRAY['Quality Control & Quality Assurance']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('radiology_technician', 'Radiology Technician', ARRAY['Radiology Technician']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('rail_signals_controls', 'Rail Signals, Communications, and Controls', ARRAY['Rail Signals, Communications, and Controls']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('rail_vehicle_maintenance', 'Rail Vehicle Maintenance', ARRAY['Rail Vehicle Maintenance']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('railway_track_maintenance', 'Railway Track Construction and Maintenance', ARRAY['Railway Track Construction and Maintenance']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('refrigeration', 'Refrigeration', ARRAY['Refrigeration']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('respiratory_therapy', 'Respiratory Therapy', ARRAY['Respiratory Therapy']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('robotics_mechatronics', 'Robotics & Mechatronics', ARRAY['Robotics & Mechatronics']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('security_systems_locksmithing', 'Security System Technology / Locksmithing', ARRAY['Security System Technology / Locksmithing']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('sheet_metal_fabrication', 'Sheet Metal Fabrication', ARRAY['Sheet Metal Fabrication']::text[], '{construction,manufacturing,transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('shipfitting_and_boat_building', 'Shipfitting and Boat Building', ARRAY['Shipfitting and Boat Building']::text[], '{transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('software_and_web_development', 'Software & Web Development', ARRAY['Software & Web Development']::text[], '{data_it}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('solar_installation', 'Solar Installation and Maintenance', ARRAY['Solar Installation and Maintenance']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('surgical_technology', 'Surgical Technology', ARRAY['Surgical Technology']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('surveying_mapping', 'Surveying and Mapping', ARRAY['Surveying and Mapping']::text[], '{construction}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('renewable_energy', 'Sustainable/Renewable Energy', ARRAY['Sustainable/Renewable Energy']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('telecommunications_technician', 'Telecommunications Technician', ARRAY['Telecommunications Technician']::text[], '{telecom}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('tool_die_mold', 'Tool, Die, Mold & Fixture Making', ARRAY['Tool, Die, Mold & Fixture Making']::text[], '{manufacturing}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('utility_public_works', 'Utility/Public Works', ARRAY['Utility/Public Works']::text[], '{public_safety}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('veterinary_technician', 'Veterinary Technician', ARRAY['Veterinary Technician']::text[], '{healthcare}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('wastewater_operations', 'Waste/Wastewater Operations', ARRAY['Waste/Wastewater Operations']::text[], '{public_safety}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('welding_fabrication', 'Welding and Fabrication', ARRAY['Welding and Fabrication','Welding & Fabricating']::text[], '{construction,manufacturing,transportation}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('wind_turbine_technology', 'Wind Turbine Technology', ARRAY['Wind Turbine Technology']::text[], '{energy}', FALSE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('other_construction', 'Other Construction-related field', ARRAY['Other Construction-related field']::text[], '{construction}', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('other_manufacturing', 'Other Manufacturing-related field', ARRAY['Other Manufacturing-related field']::text[], '{manufacturing}', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('other_energy', 'Other Energy/Utilities-related field', ARRAY['Other Energy/Utilities-related field']::text[], '{energy}', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('other_transportation', 'Other Transportation-related field', ARRAY['Other Transportation-related field']::text[], '{transportation}', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('other_healthcare', 'Other Healthcare-related field', ARRAY['Other Healthcare-related field']::text[], '{healthcare}', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('other_data_it', 'Other Data/IT-related field', ARRAY['Other Data/IT-related field']::text[], '{data_it}', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('other_telecom', 'Other Telecommunications-related field', ARRAY['Other Telecommunications-related field']::text[], '{telecom}', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);
INSERT INTO public.canonical_job_families (code, name, aliases, industries, is_other, is_active)
VALUES ('other_public_safety', 'Other Public & Emergency Services-related field', ARRAY['Other Public & Emergency Services-related field']::text[], '{public_safety}', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  industries = EXCLUDED.industries, is_other = EXCLUDED.is_other, is_active = TRUE,
  aliases = (SELECT array_agg(DISTINCT a) FROM unnest(public.canonical_job_families.aliases || EXCLUDED.aliases) AS a);

-- Retire codes from superseded auto-slug runs (renamed via overrides).
UPDATE public.canonical_job_families SET is_active = FALSE WHERE code IN (
  'robotics_and_mechatronics', 'diet_and_nutrition', 'surveying_and_mapping',
  'marine_systems_service_and_technology', 'building_automation_and_controls',
  'it_and_network_support');

-- Sector labels on the two entities that carry a field.
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS sector_code TEXT REFERENCES public.sectors(code);
ALTER TABLE public.jobs       ADD COLUMN IF NOT EXISTS sector_code TEXT REFERENCES public.sectors(code);

-- Integrity: a chosen sector must be one the linked field belongs to.
CREATE OR REPLACE FUNCTION public.check_sector_matches_field() RETURNS trigger AS $$
DECLARE fam_industries TEXT[];
BEGIN
  IF NEW.sector_code IS NULL OR NEW.canonical_job_family_id IS NULL THEN RETURN NEW; END IF;
  SELECT industries INTO fam_industries FROM public.canonical_job_families WHERE id = NEW.canonical_job_family_id;
  IF fam_industries IS NOT NULL AND array_length(fam_industries, 1) IS NOT NULL
     AND NOT (NEW.sector_code = ANY(fam_industries)) THEN
    RAISE EXCEPTION 'sector % is not valid for the selected field', NEW.sector_code
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS applicants_sector_field_check ON public.applicants;
CREATE TRIGGER applicants_sector_field_check BEFORE INSERT OR UPDATE OF sector_code, canonical_job_family_id
  ON public.applicants FOR EACH ROW EXECUTE FUNCTION public.check_sector_matches_field();
DROP TRIGGER IF EXISTS jobs_sector_field_check ON public.jobs;
CREATE TRIGGER jobs_sector_field_check BEFORE INSERT OR UPDATE OF sector_code, canonical_job_family_id
  ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.check_sector_matches_field();

